### ISSUE TITLE
Deliverable 2

### ISSUE THREAD

**Issue by bwright7luc** [LUC-Intro-to-Web-Development/lab-1-version-control-practice-with-git-and-github-bwright7luc#2]
![image](https://github.com/LUC-Intro-to-Web-Development/lab-1-version-control-practice-with-git-and-github-bwright7luc/assets/115828531/a2bd4056-4f9a-40af-8b91-fabb39d35e50)

**Comment by instructorc** [comment]
Deliverable 2 met!
